### ISSUE TITLE
Anywhere someone's name is listed in the UI, it should lead to the profile modal

### ISSUE THREAD

**Issue by rossng** [clowdr-app/clowdr#144]
Known places where this does not happen yet:

* [ ] Who's here list

Split from #106

**Comment by bcpierce00** [comment]
... also the name tags on people's camera feeds (or boxes where camera
feeds would be) in video rooms.

**Comment by EdNutting** [comment]
Both the Connected Participants and Here With You in the Who's Here list have this issue.

@bcpierce00 Name tags in video rooms already show the profile modal when you click on them.

Other known places:

* Author lists (on item pages and event summaries)
* Name tags for participants list in the Rooms sidebar
* Room members list - clicking causes you to be taken to the profile page rather than see the profile modal
* Author names in the Event Box when clicking on an event in the Schedule page

**Comment by EdNutting** [comment]
Author lists and Who's Here are done.

**Comment by EdNutting** [comment]
Author names in Event Box are done.
