### ISSUE TITLE
Allow the video room to be hidden entirely in some rooms (e.g. announcements)

### ISSUE THREAD

**Issue by rossng** [clowdr-app/clowdr#162]
Split from #75

**Comment by EdNutting** [comment]
I am slightly concerned that we're going to end up confusing users by having "group chats" and "rooms" which entirely overlap, the only difference being the group chat doesn't have a video chat by default (but users will expect that the click of a single button would generate a video chat).

Right now, I think the key missing piece is just the ability to search for chat of rooms (and items) in the chat sidebar and open the chat in the sidebar without having to go to the room I.e. just like we can search for attendees (DMs) in the sidebar without opening the person's profile, we need the same in the for rooms and items.

**Comment by EdNutting** [comment]
This is no longer an issue for Announcements, because that is no longer a room (it's a specific, special-cased chat within the system).

It appears to be a non-issue for all other rooms where the interaction is controlled by events or it's a group chat anyway. Luke's new UX for chat resolves the other separate issue mentioned here of independently finding group chats without needing to access the video room.
