### ISSUE TITLE
Automatically clean up phantom room participants

### ISSUE THREAD

**Issue by hannelita** [clowdr-app/clowdr#22]
If you join the room, there is none there, but they are still listed as active
<img width="494" alt="Screen Shot 2021-01-21 at 5 31 26 PM" src="https://user-images.githubusercontent.com/506426/105420581-9f7d0400-5c0e-11eb-8e36-07e627d21c63.png">

**Comment by EdNutting** [comment]
Yes this is a backend issue related to the database. When the database flakes out our other services can't write to it, thus they become unable to remove the participant's record. 

We need to implement two things:

1. A system for re-attempting failed requests between our services and the DB
2. Mechanisms to automatically identify and clean up dirty data like this (which is easier said than done when it comes to video systems, but hopefully we'll get there)

**Comment by rossng** [comment]
This issue should now be significantly reduced, due to two major changes:

* Significant performance optimisations have reduced database load by several orders of magnitude
* The endpoint that receives the Vonage webhook now has some more retry logic built in

However, there is still more we can do. I think one major thing is to regularly (but somewhat infrequently) resync the status of each room that we believe has participants with the ground truth from the Vonage API. This issue will now track that implementation.

**Comment by EdNutting** [comment]
Ross added a system to "double-check" with Vonage and clean up every 24hrs if necessary.
