### ISSUE TITLE
"Room starting time" doesn't make sense?

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#242]
Is the "Starts on ... at ..." text generated by Clowdr, or is it part of the description of the room?  If the former, then maybe we could find a different wording... I find the notion of a "room" starting at a particular time, which is suggested by the name of the room just above the starting time, strange.  The fix could be as simple as "Next event starts on... at...".

<img width="847" alt="image" src="https://user-images.githubusercontent.com/7014411/114254242-32128100-997c-11eb-92bb-e222f3051b24.png">

**Comment by EdNutting** [comment]
This is a description of the event that is showing to you. Ideally when nothing is live the room should show a preview of its complete schedule, not just a preview of the first event. When an event is live, you see the preview of the content (as shown here) plus the following event (usually in a grey box but with otherwise the same content).

**Comment by EdNutting** [comment]
(A simple quick fix might just be to put the start time below the event title - then you'd associate it with the event rather than the room name)

**Comment by bcpierce00** [comment]
Yes, that would be better. 
>

**Comment by EdNutting** [comment]
The quick fix will be deployed this weekend.

**Comment by EdNutting** [comment]
We have another (internal) task tracking the broader problem of previewing small parts of the schedule in rooms and item pages. I am closing this issue as the original problem has been resolved.
