### ISSUE TITLE
Urgent - please remove 'Download Calendar' from the Schedule - Full Schedule tab!

### ISSUE THREAD

**Issue by charlesweir** [clowdr-app/clowdr#343]
**Describe the bug**
The functionality works fine. But have you ever added 718 items (ESEC/FSE) to your Outlook Calendar in one click?  :-)

It's very unlikely to be what the user intended, and they're not particularly easy to remove. (Outlook for Mac seems to have some glitches in its mass deletion features).

**To Reproduce**
Click the button, download the ICS file, click on it. On Outlook Mac, at least, it only shows one item, but appears to create over 700.

**Expected behavior**
I expect it to download the items I had selected. That functionality is elsewhere.

**Screenshots**
[Sorry - missed the opportunity]

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOs 
- Mail program: Outlook for Mac 16.52

**Additional context**
If preferred, suggest simply adding a warning dialog when the user clicks that button, with a referral to same button in  My Stuff - My Events .
Or make that button simply behave as the My Events button.

**Comment by rossng** [comment]
Sorry to hear that you had trouble deleting the large number of events from your Outlook calendar! Clearly that's not a great user experience.

There are definitely use cases for downloading the full schedule, so we'd like to preserve that functionality. However, we can clearly do more to help users understand what's about to happen.

I'd be interested to hear your thoughts on how useful the each of the following UI changes would have been for you:

* A warning dialog when you clicked the 'Download calendar' button, informing you that you're about to download the entire schedule and it could contain a large number of events.
* Changing the 'Download calendar' button so that it also shows the total count of events in the calendar.
* Changing the button label to 'Download full calendar'.
* Exposing two buttons in the 'Full schedule' tab - one to download the full schedule, one to download 'my schedule'.

**Comment by EdNutting** [comment]
I intend to just change the button to be a dropdown that give you the option of "My events" or "Full Schedule (XYZ events)" so it's clear how many events the full schedule contains.

**Comment by charlesweir** [comment]
Sounds fine - great!

**Comment by EdNutting** [comment]
A solution for this has been implemented in the `next` branch with our forthcoming UX improvements (scheduled for release later this month).
