### ISSUE TITLE
Improve UI messages when chat message send fails or is delayed

### ISSUE THREAD

**Issue by amyjko** [clowdr-app/clowdr#346]
**Describe the bug**
This is a second-hand report from an attendee, but the general experience is that sometimes chat messages do not send.

**To Reproduce**

1. Join queue for a roundtable
2. Join roundtable
3. Open the chat
4. Type a message in the chat
5. Submit the chat
6. Spinning loading icon spins indefinitely and the message is never sent

**Expected behavior**
If the message has failed to send, there should be an error message; if it needs more time, there should be feedback to wait longer. Ultimately, the message should be sent.

**Desktop (please complete the following information):**

- OS: Mac OS 11.5
- Browser Chrome
- Version 92

**Comment by rossng** [comment]
Thanks for letting us know about this. There should indeed be better error/informational messages, so I'll leave this issue open to track progress on that (I'll rename it accordingly - feel free to open a new ticket with any additional info on the specific incident).

It's hard to know exactly what caused the specific incident reported here. We did recently make some changes to scale up the chat capacity in our hosted version of Clowdr - so it's possible that this will be enough.

However, it's also possible that incident was caused by something else entirely. If the attendee (or anyone else seeing this issue) is willing to help us out, it would be super useful to have:

* the browser console log
* the HAR log of network requests

You might not want to upload these to GitHub - especially network logs! But you can contact us through [our support email](https://clowdr.org/contact-us).

**Comment by amyjko** [comment]
I did ask all reporters for reproduction steps, logs, and network requests; if they manage to capture and send them to me, I'll submit.

**Comment by EdNutting** [comment]
We have recently fixed 4 long-standing connection and re-connection issues in our chat system. We have also improved the behaviour when chat messages cannot send due to a dropped network connection (there is now a timeout and an error message).
