### ISSUE TITLE
Eliminate "dead air" at the end of prerecorded talks that don't fill their slot

### ISSUE THREAD

**Issue by bcpierce00** [clowdr-app/clowdr#58]
Q&As should start when the lightning video ends, even if it's shorter than 5 min, with no filler slides.

Ed:
* Making this happen is both technically difficult and expensive. There's not an easy way to determine the running time of a video (i.e. we have known how to do it since we built the upload system, and it's non-trivial to implement). As a result, detecting the end of a video and swapping to Q&A is quite hard. (The current filler system relies on AWS' "fallback" mechanism which notices the end of the video input and falls back to the filler video until new input as available.)

BCP: That's a shame.  I guess we can hope that _most_ talks will be roughly the right length, but if there's one that's significantly short, both audience and authors will be annoyed.

**Comment by EdNutting** [comment]
@rossng mentioned it may be possible to detect when everyone has disconnected from a backstage room, and thus kill the room (and its RTMP feed), and with a little extra magic that would auto-switch us back into the filler video. 

(This is not high priority atm)

**Comment by rossng** [comment]
There are actually two separate issues here. 

First, there is switching to the filler video when the live broadcast ends. It's actually surprisingly tricky to detect this, but I think it can be implemented in a fairly isolated way.

Second, there is switching to Q&A automatically when the previous event ends early. 

I think we have to be a little careful about this - we should probably only perform the auto-switch when the two events are contiguous and share the same underlying content group. Otherwise we may end up with situations where (say) a technical presentation is followed by an unrelated panel discussion (marked up as a Q&A event). If the technical presentation ends early, the panel discussion would suddenly start at completely the wrong time.

This second part is somewhat trickier to implement, and I'm splitting it out into a new issue.

**Comment by rossng** [comment]
Split out into other issues.
