### ISSUE TITLE
clowdr mistakenly reports no permission to use mic

### ISSUE THREAD

**Issue by nrnrnr** [clowdr-app/clowdr#96]
I had to reboot my machine to get clowdr to deliver audio and video from others.

Then when I tried to activate my own mic, clowdr objected that it didn't have permission.  I checked and indeed `app.clowdr.org` *did* have permission from Chrome to use the mic.

Eventually I found that the reboot had somehow reset clowdr so it didn't know which device to use as the mic.    On the Settings menu the mic choice just read "choose microphone."

Not sure how to resolve this issue, but perhaps when saying it lacks permission, clowdr could also display _which_ device it thinks it is using as mic (or camera)

**Comment by EdNutting** [comment]
Hi Norman,

We eventually figured this one out - a while ago but I omitted to update this issue so here's the explanation.

Clowdr was storing the previously selected device id, so that when a user returns to the site they don't have to go around the houses again to select their mic/cam/etc. Unfortunately, this meant that if a user previously selected a device that subsequently became unavailable (disconnected, permission denied, or similar), Clowdr's device chooser got stuck. It always tried to request permissions for that device without every succeeding and without clearing its cache of the chosen device. A system restart would often clear out the device state (and cause cleared caches to be applied/detected in Clowdr).

We solved it by clearing the stored device id immediately after a permission failure and suppressing the error message in that instance. This leads to the expected and much cleaner experience, without the "totally stuck" scenario.

Best,
Ed
